import { Alert, Badge, Button, Checkbox, Group, Paper, SimpleGrid, Stack, Text } from "@mantine/core";
import { PageHeader } from "@/components/leadely/page-header";
import { SectionPanel } from "@/components/leadely/section-panel";
import { Table, TableTbody, TableTd, TableTh, TableThead, TableTr } from "@/components/leadely/table";
import { loadPlatformMcp, setMcpOAuthClientStatusAction, updateMcpSettingsAction } from "@/features/mcp/server/actions";

export default async function PlatformMcpPage() {
  const data = await loadPlatformMcp();
  const active = data.connections.filter((item) => item.status === "active").length;
  const errors = data.calls.filter((item) => item.status === "error").length;
  const averageLatency = data.calls.length ? Math.round(data.calls.reduce((sum, item) => sum + item.duration_ms, 0) / data.calls.length) : 0;
  return <Stack gap="md">
    <PageHeader title="MCP platform" subtitle="Control rollout and inspect workspace MCP activity without exposing access tokens." />
    <SimpleGrid cols={{ base: 2, md: 5 }} spacing="sm"><Paper withBorder p="md"><Text size="xs" c="dimmed">Connections</Text><Text size="xl" fw={700}>{data.connections.length}</Text></Paper><Paper withBorder p="md"><Text size="xs" c="dimmed">Active</Text><Text size="xl" fw={700}>{active}</Text></Paper><Paper withBorder p="md"><Text size="xs" c="dimmed">Recent calls</Text><Text size="xl" fw={700}>{data.calls.length}</Text></Paper><Paper withBorder p="md"><Text size="xs" c="dimmed">Errors</Text><Text size="xl" fw={700}>{errors}</Text></Paper><Paper withBorder p="md"><Text size="xs" c="dimmed">Average latency</Text><Text size="xl" fw={700}>{averageLatency} ms</Text></Paper></SimpleGrid>
    {!data.canMutate ? <Alert color="blue">Support can inspect MCP activity. Only Super Admin can change rollout settings.</Alert> : null}
    <SectionPanel title="Rollout"><form action={async (formData) => { "use server"; await updateMcpSettingsAction(formData); }}><Group align="center" justify="space-between"><Group><Checkbox name="enabled" label="MCP enabled" defaultChecked={data.settings?.enabled} disabled={!data.canMutate} /><Checkbox name="read_tools_enabled" label="Read tools enabled" defaultChecked={data.settings?.read_tools_enabled} disabled={!data.canMutate} /><Checkbox name="write_tools_enabled" label="Approval-gated write tools" defaultChecked={data.settings?.write_tools_enabled} disabled={!data.canMutate} /></Group>{data.canMutate ? <Button type="submit" size="compact-sm">Save</Button> : null}</Group></form></SectionPanel>
    <SectionPanel title="OAuth clients" padded={false}><Table><TableThead><TableTr><TableTh>Client</TableTh><TableTh>Redirect URIs</TableTh><TableTh>Status</TableTh><TableTh>Last used</TableTh><TableTh /></TableTr></TableThead><TableTbody>{data.oauthClients.map((client) => <TableTr key={client.client_id}><TableTd>{client.client_name}<Text size="xs" c="dimmed">{client.client_id.slice(0, 22)}…</Text></TableTd><TableTd><Text size="xs">{client.redirect_uris.join(", ")}</Text></TableTd><TableTd><Badge variant="light" color={client.status === "active" ? "teal" : "gray"}>{client.status}</Badge></TableTd><TableTd>{client.last_used_at ? new Date(client.last_used_at).toLocaleString() : "Never"}</TableTd><TableTd>{data.canMutate ? <form action={setMcpOAuthClientStatusAction}><input type="hidden" name="client_id" value={client.client_id} /><input type="hidden" name="status" value={client.status === "active" ? "revoked" : "active"} /><Button type="submit" size="compact-sm" variant="subtle" color={client.status === "active" ? "red" : "teal"}>{client.status === "active" ? "Revoke" : "Reactivate"}</Button></form> : null}</TableTd></TableTr>)}</TableTbody></Table></SectionPanel>
    <SectionPanel title="Connections" padded={false}><Table><TableThead><TableTr><TableTh>Name</TableTh><TableTh>Workspace</TableTh><TableTh>Scopes</TableTh><TableTh>Status</TableTh><TableTh>Last used</TableTh></TableTr></TableThead><TableTbody>{data.connections.map((item) => <TableTr key={item.id}><TableTd>{item.name}<Text size="xs" c="dimmed">{item.token_prefix}</Text></TableTd><TableTd>{data.workspaceNames[item.workspace_id] || item.workspace_id}</TableTd><TableTd><Text size="xs">{item.scopes.join(", ")}</Text></TableTd><TableTd><Badge variant="light" color={item.status === "active" ? "teal" : "gray"}>{item.status}</Badge></TableTd><TableTd>{item.last_used_at ? new Date(item.last_used_at).toLocaleString() : "Never"}</TableTd></TableTr>)}</TableTbody></Table></SectionPanel>
  </Stack>;
}
